ft-user Signup/Register-#184749873
atlp-rwanda/e-comm-team-emma25-fe pull request #22
Opened 2023-04-17 08:04 UTC by jeandamas

- GIVEN user successfully signs up/registers.
- WHEN user passes appropriate signup parameters
- THEN user should be able to sign up.

2023-04-20 14:33 UTC, TresorRw requested changes
- You can react-hook-form for proper and easy form handling 
- Use a toast notification instead of alerts

2023-04-20 15:34 UTC, Rukundojoseph approved these changes, later dismissed

2023-04-20 16:18 UTC, fabrice-rw submitted a review, later dismissed

2023-04-21 14:28 UTC, TresorRw approved these changes

2023-04-21 14:39 UTC, fabrice-rw approved these changes

2023-04-24 07:17 UTC, merged